export const dummy = [
  //{
  //   tables: [
  //     {
  //       _id: "1a2b3c4d-5678-90ef-ghij-klmnopqrstuv",
  //       name: "Customers",
  //       description: "Main customer information",
  //       variables: [
  //         {
  //           _id: "var1-1111-2222-3333-444444444444",
  //           name: "id",
  //           desc: "Description for id field",
  //           type: "string",
  //           cle: false,
  //           color: "#FF5733",
  //           typeVar: "standard",
  //           settings: [],
  //           hasMapping: true,
  //         },
  //         {
  //           _id: "var2-1111-2222-3333-444444444444",
  //           name: "name",
  //           desc: "Description for name field",
  //           type: "string",
  //           cle: true,
  //           color: "#33FF57",
  //           typeVar: "standard",
  //           settings: [],
  //           hasMapping: false,
  //         },
  //       ],
  //       position: {
  //         pos_x: 100,
  //         pos_y: 150,
  //       },
  //       cursorIsIn: false,
  //       date: "2023-05-15T10:00:00Z",
  //       __v: 0,
  //     },
  //   ],
  //   mappings: [
  //     {
  //       type: "Enum",
  //       name: "Status",
  //       members: [
  //         {
  //           key: "active",
  //           description: "Active status",
  //           note: "Currently active",
  //         },
  //         {
  //           key: "inactive",
  //           description: "Inactive status",
  //           note: "",
  //         },
  //       ],
  //     },
  //   ],
  //   links: [
  //     {
  //       type: "Ref",
  //       left: "Customers.id",
  //       relationship: "has_many",
  //       right: "Orders.customer_id",
  //     },
  //   ],
  // },
  // {
  //   tables: [
  //     {
  //       _id: "5e6f7g8h-9012-34ij-klmn-opqrstuvwxyz",
  //       name: "Products",
  //       description: "Product catalog data",
  //       variables: [
  //         {
  //           _id: "var3-5555-6666-7777-888888888888",
  //           name: "price",
  //           desc: "Description for price field",
  //           type: "number",
  //           cle: false,
  //           color: "#3357FF",
  //           typeVar: "standard",
  //           settings: [],
  //           hasMapping: true,
  //         },
  //       ],
  //       position: {
  //         pos_x: 300,
  //         pos_y: 200,
  //       },
  //       cursorIsIn: false,
  //       date: "2023-05-16T11:30:00Z",
  //       __v: 0,
  //     },
  //   ],
  //   mappings: [
  //     {
  //       type: "Enum",
  //       name: "Category",
  //       members: [
  //         {
  //           key: "electronics",
  //           description: "Electronic items",
  //           note: "",
  //         },
  //       ],
  //     },
  //   ],
  //   links: [],
  // },
  // {
  //   tables: [
  //     {
  //       _id: "9i0j1k2l-3456-78mn-opqr-stuvwxyzabcd",
  //       name: "Orders",
  //       description: "Order transactions",
  //       variables: [
  //         {
  //           _id: "var4-9999-0000-1111-222222222222",
  //           name: "quantity",
  //           desc: "Description for quantity field",
  //           type: "number",
  //           cle: true,
  //           color: "#F333FF",
  //           typeVar: "standard",
  //           settings: [],
  //           hasMapping: false,
  //         },
  //       ],
  //       position: {
  //         pos_x: 500,
  //         pos_y: 250,
  //       },
  //       cursorIsIn: false,
  //       date: "2023-05-17T09:15:00Z",
  //       __v: 0,
  //     },
  //   ],
  //   mappings: [],
  //   links: [
  //     {
  //       type: "Ref",
  //       left: "Products.id",
  //       relationship: "belongs_to",
  //       right: "Orders.product_id",
  //     },
  //   ],
  // },
  {
    tables: [
      {
        cursorIsIn: false,
        position: {
          pos_x: 0,
          pos_y: 0,
        },
        _id: "2",
        name: "ateliers",
        description: "Table des utilisateurs",
        variables: [
          {
            _id: "2-0",
            name: "id",
            desc: "",
            type: "integer",
            cle: false,
            color: "lightgrey",
            typeVar: "integer",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "2-1",
            name: "titre",
            desc: "",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "2-2",
            name: "date",
            desc: "",
            type: "timestamp",
            cle: false,
            color: "lightgrey",
            typeVar: "timestamp",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "2-3",
            name: "list_users",
            desc: "liste des utilisateurs de l'atelier",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: true,
          },
        ],
        date: "2025-06-25",
        __v: 0,
        hideInMap: true,
      },
      {
        cursorIsIn: false,
        position: {
          pos_x: 0,
          pos_y: 0,
        },
        _id: "0",
        name: "users",
        description: "Table des utilisateurs",
        variables: [
          {
            _id: "0-0",
            name: "id",
            desc: "",
            type: "integer",
            cle: true,
            color: "lightgrey",
            typeVar: "integer",
            settings: ["pk", '"unique"'],
            hasMapping: false,
          },
          {
            _id: "0-1",
            name: "username",
            desc: "",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "0-2",
            name: "role",
            desc: "",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "0-3",
            name: "'test id'",
            desc: "",
            type: "integer",
            cle: true,
            color: "lightgrey",
            typeVar: "integer",
            settings: ["pk", '"unique"'],
            hasMapping: false,
          },
          {
            _id: "0-4",
            name: "created_at",
            desc: "",
            type: "timestamp",
            cle: false,
            color: "lightgrey",
            typeVar: "timestamp",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "0-5",
            name: "name",
            desc: "",
            type: "string",
            cle: false,
            color: "lightgrey",
            typeVar: "string",
            settings: ['"not null"', "invalid_setting"],
            hasMapping: false,
          },
        ],
        date: "2025-06-25",
        __v: 0,
        hideInMap: false,
      },
      {
        cursorIsIn: false,
        position: {
          pos_x: 0,
          pos_y: 0,
        },
        _id: "1",
        name: "yves",
        description: "",
        variables: [
          {
            _id: "1-0",
            name: "id",
            desc: "",
            type: "integer",
            cle: false,
            color: "lightgrey",
            typeVar: "integer",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "1-1",
            name: "titre",
            desc: "",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "1-2",
            name: "date",
            desc: "",
            type: "timestamp",
            cle: false,
            color: "lightgrey",
            typeVar: "timestamp",
            settings: [],
            hasMapping: false,
          },
          {
            _id: "1-3",
            name: "list_users",
            desc: "",
            type: "varchar",
            cle: false,
            color: "lightgrey",
            typeVar: "varchar",
            settings: [],
            hasMapping: true,
          },
        ],
        date: "2025-06-25",
        __v: 0,
        hideInMap: false,
      },
    ],
    mappings: [
      {
        type: "Enum",
        table: "Global",
        name: "list_users",
        members: [
          {
            key: "created",
            description: "status at the beginning of the process",
            note: "Waiting to be processed",
          },
          {
            key: "running",
            description: "statut when activate",
            note: "",
          },
          {
            key: "done",
            description: "status after completion",
            note: "",
          },
          {
            key: "failure error",
            description: "status when error occurs",
            note: "",
          },
        ],
      },
    ],
    links: [
      {
        type: "Ref",
        left: "ateliers.list_users",
        relationship: ">",
        right: "users.id",
      },
      {
        type: "Ref",
        left: "ateliers.id",
        relationship: "<>",
        right: "users.id",
      },
      {
        type: "Ref",
        left: "yves.id",
        relationship: "<>",
        right: "users.'test id'",
      },
    ],
  },
];
