export const exemple = {
  tables: [
    {
      cursorIsIn: false,
      position: {
        pos_x: 0,
        pos_y: 0,
      },
      _id: "0",
      name: "users",
      description: "Table des utilisateurs",
      variables: [
        {
          _id: "0-0",
          name: "id",
          desc: "",
          type: "integer",
          cle: true,
          color: "lightgrey",
          typeVar: "integer",
          settings: ["pk", '"unique"'],
          hasMapping: false,
        },
        {
          _id: "0-1",
          name: "'test id'",
          desc: "",
          type: "integer",
          cle: true,
          color: "lightgrey",
          typeVar: "integer",
          settings: ["pk", '"unique"'],
          hasMapping: false,
        },
        {
          _id: "0-2",
          name: "username",
          desc: "",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "0-3",
          name: "role",
          desc: "",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "0-4",
          name: "created_at",
          desc: "",
          type: "timestamp",
          cle: false,
          color: "lightgrey",
          typeVar: "timestamp",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "0-5",
          name: "name",
          desc: "",
          type: "string",
          cle: false,
          color: "lightgrey",
          typeVar: "string",
          settings: ['"not null"', "invalid_setting"],
          hasMapping: false,
        },
      ],
      date: "2025-05-18",
      __v: 0,
    },
    {
      cursorIsIn: false,
      position: {
        pos_x: 0,
        pos_y: 0,
      },
      _id: "1",
      name: "yves",
      description: "",
      variables: [
        {
          _id: "1-0",
          name: "id",
          desc: "",
          type: "integer",
          cle: false,
          color: "lightgrey",
          typeVar: "integer",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "1-1",
          name: "titre",
          desc: "",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "1-2",
          name: "date",
          desc: "",
          type: "timestamp",
          cle: false,
          color: "lightgrey",
          typeVar: "timestamp",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "1-3",
          name: "list_users",
          desc: "",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
      ],
      date: "2025-05-18",
      __v: 0,
    },
    {
      cursorIsIn: false,
      position: {
        pos_x: 0,
        pos_y: 0,
      },
      _id: "2",
      name: "ateliers",
      description: "Table des utilisateurs",
      variables: [
        {
          _id: "2-0",
          name: "id",
          desc: "",
          type: "integer",
          cle: false,
          color: "lightgrey",
          typeVar: "integer",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "2-1",
          name: "titre",
          desc: "",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "2-2",
          name: "date",
          desc: "",
          type: "timestamp",
          cle: false,
          color: "lightgrey",
          typeVar: "timestamp",
          settings: [],
          hasMapping: false,
        },
        {
          _id: "2-3",
          name: "list_users",
          desc: "liste des utilisateurs de l'atelier",
          type: "varchar",
          cle: false,
          color: "lightgrey",
          typeVar: "varchar",
          settings: [],
          hasMapping: false,
        },
      ],
      date: "2025-05-18",
      __v: 0,
    },
  ],
  mappings: [
    {
      type: "Enum",
      table: "Global",
      name: "job_status",
      members: [
        {
          key: "created",
          description: "status at the beginning of the process",
          note: "Waiting to be processed",
        },
        {
          key: "running",
          description: "statut when activate",
          note: "",
        },
        {
          key: "done",
          description: "status after completion",
          note: "",
        },
        {
          key: "failure error",
          description: "status when error occurs",
          note: "",
        },
      ],
    },
  ],
  links: [
    {
      type: "Ref",
      left: "ateliers.list_users",
      relationship: ">",
      right: "users.id",
    },
    {
      type: "Ref",
      left: "ateliers.id",
      relationship: "<>",
      right: "users.id",
    },
    {
      type: "Ref",
      left: "yves.id",
      relationship: "<>",
      right: "users.'test id'",
    },
  ],
};
